(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g,l="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},m=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},n=m(this),p;
if("function"==typeof Object.setPrototypeOf)p=Object.setPrototypeOf;else{var q;a:{var r={a:!0},t={};try{t.__proto__=r;q=t.a;break a}catch(a){}q=!1}p=q?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var u=p,w=function(a,b){a.prototype=l(b.prototype);a.prototype.constructor=a;if(u)u(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.aa=b.prototype};var x=function(a,b,c){for(var d=b/c,e,f,h,k=0;k<a.length;k++)if(e=a[k],"img"==e.tagName.toLowerCase()||"gwd-image"==e.tagName.toLowerCase())f=e.offsetWidth/e.offsetHeight,d>f?(h=c*f,f=c):(h=b,f=b/f),e.style.width=h+"px",e.style.height=f+"px"};var y=function(a,b){return window.setTimeout(a,b)};var z=function(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d);return d},A=function(a,b,c){c=void 0===c?null:c;var d=void 0===d?null:d;y(function(){var e=z(a,b,c);d&&d(e)},0)},B=function(a,b){var c=function(d){a.removeEventListener("attached",c);b(d)};a.addEventListener("attached",c)},C=function(a){var b=!1,c=null;return function(){b=!0;c||(b&&(a(),b=!1),c=y(function(){c=null;b&&(a(),b=!1)},250))}};var D=["-ms-","-moz-","-webkit-",""];var E=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},F=function(a){if(E(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&E(a))return a;return null};var G=function(a){var b=[];if(a){a=a.split(",");for(var c=0;c<a.length;c++)if(!/^[\s\xa0]*$/.test(a[c])){var d=b,e=d.push;var f=a[c];f=f.trim();f=window.Enabler?window.Enabler.getUrl(f):f;var h=document.createElement("gwd-image");h.setAttribute("source",f);e.call(d,h)}}return b},H=function(a,b){return(a%b+b)%b},I=function(a,b,c,d){d=void 0===d?1:d;return H(a+("left"==b||"backwards"==b?-d:d),c)};var J=function(a){var b=a.currentIndex-1;return b-b%a.frameSnapInterval},K=function(a){this.j=a;this.o=null;this.Z=!0;this.D=!1};
K.prototype.play=function(a,b,c){var d=this;b=void 0===b?"forwards":b;if(this.j.frameCount&&null==this.o){if(c){var e=Math.floor(a/c);a=c}else e=this.j.frameCount,a/=e;var f=[],h=J(this.j);c=h;for(var k=0;k<e;k++){if(0<k||!this.Z)c=I(c,b,this.j.frameCount);f.push(c)}b=function(){if(f.length){var v=f.shift();d.D=!0;d.j.goToFrame(v+1);d.D=!1;z("frameautoplayed",d.j,{id:v+1})}else d.stop(!0),d.j.goToFrame(h+1)};this.o=window.setInterval(b,a);setTimeout(b)}};
K.prototype.stop=function(a){a=void 0===a?!1:a;!this.D&&this.o&&(window.clearInterval(this.o),A("autoplayended",this.j,{completed:a}),this.o=null)};var L=["pause-front-media","resume-next-media"],M=function(){var a=HTMLElement.call(this)||this;a.frames=[];a.g=null;a.h=0;a.u=1;a.J=new K(a);a.Y=!1;a.$=!1;return a};w(M,HTMLElement);M.prototype.attributeChangedCallback=function(a,b,c){switch(a){case "pause-front-media":this.Y="true"==c;break;case "resume-next-media":this.$="true"==c}};M.prototype.gwdIsLoaded=function(){return!0};M.prototype.gwdLoad=function(){};
M.prototype.goToFrame=function(a){this.stopRotation();0!=this.h&&(a>this.h?a=this.h:1>a&&(a=1),this.g=a-1)};var N=function(a,b,c,d){if(null!=a.g){var e=I(a.g,b,a.u*Math.ceil(a.h/a.u),a.u);!d&&("forwards"==b&&e<a.g||"backwards"==b&&e>a.g)||a.goToFrame(e+1,c)}};g=M.prototype;g.goBackwards=function(a,b){N(this,"backwards",void 0===a?"slide":a,void 0===b?!0:b)};g.goForwards=function(a,b){N(this,"forwards",void 0===a?"slide":a,void 0===b?!0:b)};g.rotateOnce=function(a,b){this.J.play(void 0===a?0:a,b)};
g.stopRotation=function(){this.J.stop()};g.getFrame=function(a){if(0!=this.h)return this.frames[a-1]};var O=function(a,b,c){z(b,a,{id:c||a.currentIndex})};n.Object.defineProperties(M.prototype,{currentIndex:{configurable:!0,enumerable:!0,get:function(){return 0<this.h?this.g+1:void 0}},frameSnapInterval:{configurable:!0,enumerable:!0,get:function(){return this.u}},frameCount:{configurable:!0,enumerable:!0,get:function(){return this.h}}});
n.Object.defineProperties(M,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return L}}});var P=["images","wrap","pause-front-media","resume-next-media"],Q=function(){var a=M.call(this)||this;a.G=!1;a.i=null;a.I=0;a.m=null;a.S=a.W.bind(a);a.R=a.X.bind(a);a.P=a.V.bind(a);a.C=z.bind(null,"firstinteraction",a);a.N=a.T.bind(a);a.O=C(a.U.bind(a));a.B=[];a.L=0;a.l=-1;a.v=null;a.K=!1;a.s=!1;a.A=null;a.F=!1;a.M=!1;return a};w(Q,M);g=Q.prototype;
g.connectedCallback=function(){if(!this.F){var a=document.createElement("gwd-gesture");a.className="gesture";this.m=a;this.F=!0;this.M&&R(this)}this.m.addEventListener("trackstart",this.S,!1);this.m.addEventListener("track",this.R,!1);this.m.addEventListener("tap",this.P,!1);this.gwdIsLoaded()||((a=F(this))?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad());window.addEventListener("resize",this.O,!1)};
g.disconnectedCallback=function(){window.removeEventListener("resize",this.O,!1);var a=this.m;a.removeEventListener("trackstart",this.S,!1);a.removeEventListener("track",this.R,!1);a.removeEventListener("tap",this.P,!1);-1!=this.l&&(S(this,this.l),T(this))};
g.attributeChangedCallback=function(a,b,c,d){switch(a){case "images":T(this);this.K=!0;this.h=0;this.g=-1;this.frames=G(c);R(this);break;case "wrap":this.s=this.hasAttribute("wrap");break;default:M.prototype.attributeChangedCallback.call(this,a,b,c,d)}};
g.goToFrame=function(a,b,c){b=void 0===b?"slide":b;var d=a-1;T(this);if(0<=d&&d<this.frameCount&&d!=(-1!=this.l?this.l:this.g)){if(!c){c=this.g;var e=Math.abs(d-c);c=d>c==(!this.s||this.frameCount/2>e)?"forwards":"backwards"}O(this,"frameactivated",a);this.H(I(this.g,c,this.frameCount),d,b,c,300)}};
g.rotateOnce=function(a,b){var c=this;T(this);var d=a&&b&&"string"==typeof a&&"number"==typeof b,e=(d?a:b)||"forwards",f=(d?b:a)||300*this.frameCount;if(1<this.frameCount){var h=this.g,k=I(this.g,e,this.frameCount);y(function(){c.H(k,h,"slide",e,f/c.frameCount,!0)},0)}};g.stopRotation=function(){T(this)};g.gwdIsLoaded=function(){return this.G};
g.gwdLoad=function(){if(!this.G&&!this.i){if(this.K)var a=G(this.getAttribute("images"));else{a=this.childNodes;for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c];e.nodeType==Node.ELEMENT_NODE&&b.push(e)}a=b}this.frames=a;R(this)}};
var R=function(a){if(a.F){for(;a.firstChild;)a.removeChild(a.firstChild);a.i&&a.i.removeEventListener("pageload",a.N,!1);for(var b=a.frames,c=document.createElement("gwd-page"),d=0;d<b.length;d++){var e=b[d],f=void 0;f=void 0===f?!1:f;for(var h=0;h<D.length;h++){var k=D[h]+"user-select";var v=(f?D[h]:"")+"none";e.style.setProperty(k,v)}e.classList.add("frame");c.appendChild(e)}B(c,c.gwdLoad.bind(c));a.i=c;a.i.addEventListener("pageload",a.N,!1);a.appendChild(a.m);a.appendChild(a.i)}else a.M=!0};
g=Q.prototype;g.T=function(a){this.i===a.target&&(x(this.frames,this.clientWidth,this.clientHeight),this.G=!0,this.removeChild(this.i),this.h=this.frames.length,this.B=[],this.L=this.frameCount,S(this,0),this.i=null,z("imagesloaded",this),z("allframesloaded",this),this.hasAttribute("autoplay")&&y(this.rotateOnce.bind(this),0),z("ready",this))};g.U=function(){x(this.frames,this.clientWidth,this.clientHeight)};g.W=function(){T(this);0<this.frameCount&&(this.I=this.g)};
g.X=function(a){this.frameCount&&(this.C&&(this.C(),this.C=null),a=Math.round(a.dx/50),a=this.s?H(this.I+a,this.frameCount):Math.max(0,Math.min(this.frameCount-1,this.I+a)),this.g!=a&&this.frames[a]&&(O(this,"frameactivated",a+1),S(this,a)))};g.V=function(){this.frameCount&&O(this,"frametap")};var S=function(a,b){if(a.g!=b&&a.frames[b]){a.g=b;var c=a.A;a.A=a.frames[b];a.appendChild(a.A);c&&a.removeChild(c);O(a,"frameshown");a.B[b]||(a.B[b]=!0,--a.L||A("allframesviewed",a))}};
Q.prototype.H=function(a,b,c,d,e,f){f=void 0===f?!1:f;"none"==c&&(a=b);S(this,a);f&&O(this,"frameactivated",a+1);a!=b?(this.l=b,a=I(a,d,this.frameCount),this.v=y(this.H.bind(this,a,b,c,d,e,f),e)):(this.v=null,this.l=-1)};var T=function(a){-1!=a.l&&(window.clearTimeout(a.v),a.v=null,a.l=-1,O(a,"frameactivated",a.g))};Q.prototype.getFrame=function(a){return this.frames[a-1]};Q.prototype.goForwards=function(){var a=H(this.g+1,this.frameCount);!this.s&&a<this.g||this.goToFrame(a+1)};
Q.prototype.goBackwards=function(){var a=H(this.g-1,this.frameCount);!this.s&&a>this.g||this.goToFrame(a+1)};n.Object.defineProperties(Q,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return P}}});customElements.define("gwd-360gallery",Q);}).call(this);
