(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var d="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},e=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},f=e(this),h;
if("function"==typeof Object.setPrototypeOf)h=Object.setPrototypeOf;else{var k;a:{var l={a:!0},m={};try{m.__proto__=l;k=m.a;break a}catch(a){}k=!1}h=k?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var n=h,p=function(a,b){a.prototype=d(b.prototype);a.prototype.constructor=a;if(n)n(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var g=Object.getOwnPropertyDescriptor(b,c);g&&Object.defineProperty(a,c,g)}else a[c]=b[c];a.i=b.prototype};var q=function(a){return a.hasAttribute("direction")?a.getAttribute("direction"):"lefttoright"};var r=function(){var a=HTMLElement.call(this)||this;a.g=null;a.frameWidth=0;a.frameHeight=0;return a};p(r,HTMLElement);r.prototype.connectedCallback=function(){this.h||(this.h=window.setTimeout(this.gwdLoad.bind(this),0))};
r.prototype.gwdLoad=function(){this.h&&(clearTimeout(this.h),this.h=void 0);var a=this.parentElement.querySelector("canvas");a&&(this.g=a.getContext("2d"),this.frameWidth=parseInt(a.style.width,10),this.frameHeight=parseInt(a.style.height,10));var b=void 0===b?null:b;a=document.createEvent("CustomEvent");a.initCustomEvent("ready",!0,!0,b);this.dispatchEvent(a)};r.prototype.gwdIsLoaded=function(){return!!this.g};r.prototype.renderAnimation=function(){};
var t=function(a,b,c,g){a.g.drawImage(b,c,g,a.frameWidth,a.frameHeight)};r.prototype.getSupportedSwipeDirection=function(){if("undefined"===typeof this.direction)return[0,0];switch(this.direction){case "lefttoright":return[1,0];case "righttoleft":return[-1,0];case "toptobottom":return[0,1];case "bottomtotop":return[0,-1];default:return[0,0]}};r.prototype.setDirection=function(){};r.prototype.resetDirection=function(){};var u=["direction"],v=function(){return r.apply(this,arguments)||this};p(v,r);v.prototype.connectedCallback=function(){this.direction=q(this);r.prototype.connectedCallback.call(this)};v.prototype.attributeChangedCallback=function(a){switch(a){case "direction":this.direction=q(this)}};v.prototype.setDirection=function(a){this.direction=a};v.prototype.resetDirection=function(){this.direction=q(this)};
v.prototype.renderAnimation=function(a,b,c){this.g.save();this.g.clearRect(0,0,this.frameWidth,this.frameHeight);switch(this.direction){case "righttoleft":t(this,b,(1-c)*this.frameWidth,0);t(this,a,-c*this.frameWidth,0);break;case "toptobottom":t(this,b,0,(c-1)*this.frameHeight);t(this,a,0,c*this.frameHeight);break;case "bottomtotop":t(this,b,0,(1-c)*this.frameHeight);t(this,a,0,-c*this.frameHeight);break;default:t(this,b,(c-1)*this.frameWidth,0),t(this,a,c*this.frameWidth,0)}this.g.restore()};
f.Object.defineProperties(v,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return u}}});customElements.define("gwd-push",v);}).call(this);
